### PR TITLE
Update relationship_tests.py

### PR DESCRIPTION
**Pull request by tonjo**
Deeper relationship .filter tests.

### CODE REVIEW

**Comment by mhluongo** [comment]
@tonjo it looks like there might be an indentation error? Here are the test results https://travis-ci.org/scholrly/neo4django/jobs/10829996

**Comment by tonjo** [comment]
Yep, definitely.
It should be ok now.

**Comment by mhluongo** [comment]
@tonjo after cleaning up the test (at least one logic error and removing the `vars()` bit) it appears to pass- see https://travis-ci.org/scholrly/neo4django/builds/11446461 .

**Comment by tonjo** [comment]
Don't know what to think, still having that issues...
What can a stable configuration be?

Neo4j 1.8.2 (I tested also 1.9.2)
neo4django git-cloned
Django 1.5.4 ?

**Pull request merged**
