### PR TITLE
Added timezone-aware DateTimeProperty subclass

### PR DESCRIPTION
**Pull request by necaris**
Adds a timezone-aware DateTimeProperty subclass DateTimeTZProperty, using dateutil.tz (or locally redefined classes) to represent timezone offsets. Should be fully backward-compatible with DateTimeProperty. Also added tests.

### CODE REVIEW

**Comment by mhluongo** [comment]
Sorry I didn't see this earlier, just changed my notification settings. Looks good!

I think it'd make more sense to make python-dateutil a requirement than include the chunk of BSD, and a regression test was broken (test_filter_date_range), but I'll take care of that stuff in a jiffy.

Really appreciate the contribution. If requiring dateutil is a problem for your use case, let me know and we can come up with a fix.

**Comment by necaris** [comment]
No worries -- happy to rework the patch if it helps. My use-case
already requires dateutil, I just didn't want to impose a dependency
on you :-)

I expect I'm doing something wrong but I've never gotten the tests to
pass cleanly even on a vanilla checkout, I'm afraid.

On Tue, Jan 3, 2012 at 22:59, Matt Luongo
reply@reply.github.com
wrote:

> Sorry I didn't see this earlier, just changed my notification settings. Looks good!
> 
> I think it'd make more sense to make python-dateutil a requirement than include the chunk of BSD, and a regression test was broken (test_filter_date_range), but I'll take care of that stuff in a jiffy.
> 
> Really appreciate the contribution. If requiring dateutil is a problem for your use case, let me know and we can come up with a fix.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scholrly/neo4django/pull/45#issuecomment-3347783

## 

Rami Chowdhury
"A mind all logic is like a knife all blade - it makes the hand bleed
that uses it." -- Rabindranath Tagore
+44-7581-430-517 / +1-408-597-7068 / +88-0189-245544

**Comment by mhluongo** [comment]
Eh, I'm okay with the dep- if it bothers someone in the future it can be made optional.

re: testing - Hmm, if you keep hacking maybe it'd be worth figuring out- any errors in particular? Sorry if it's obvious, but did you see the bit about running the test suite at the bottom of the README?

Anyway, thanks again for the patch- I'm excited to see another startup doing Django/Neo4j.

**Comment by lukeorland** [comment]
FYI Issue #148 affects the DateTimeTZProperty class.

**Pull request merged**
