### PR TITLE
Add a use_string kwarg to ArrayProperty to store data as a token separated string

### PR DESCRIPTION
**Pull request by vistorve**
use_string kwarg when set to True will override default behavior of ArrayProperty
and store array data as a token separated string in neo4j instead of an array.

This is useful for users who interact with their neo4j instance with tools other
than neo4django and so cannot make use of the gremlin magic that neo4django
uses behind the scenes. Neo4j's current REST API does not support
storing empty arrays because it cannot determine the data type from the passed
in JSON.

The user can specify the token to use as the separator as well as the token to
use for escaping the separator with the values themselves. to_neo() will take care
of escaping the separator within the values themselves. The only caveat that this
brings in is that all values become strings as to_neo() does not store type information
along with each value.

Regression tests produced two errors/failures but these are also present in the current
pull from neo4django's master branch.

### CODE REVIEW

**Comment by mhluongo** [comment]
Good idea- thanks for the request.

**Comment by mhluongo** [comment]
What version of Neo are you guys using? I only have 1 regression test failing (test_array_property_validator), but I've noticed that some people are having a test_select_related failure though I can't replicate it.

**Comment by vistorve** [comment]
We are using 1.5.2 which I thought was required due to neo4jrestclient.

Failing tests:

2 test(s) failed their regression test: 
    neo4django.tests.nodequeryset_tests.test_select_related,
    neo4django.tests.property_tests.test_array_property_validator

**Comment by mhluongo** [comment]
Hm, we're on 1.6.3, though I'm not sure whether that's the cause. I need to get Travis CI working properly to automate some of these version uncertainties away.

Thanks for the report- I won't try to debug the issue through you :), but I'll give replicating it another go.

**Pull request merged**
