### PR TITLE
Backend fix User model (avoid from_model trick)

### PR DESCRIPTION
**Pull request by tonjo**
Using `authenticate` gave always `graph_auth.User`.
Taken from django's auth, `get_user_model` will ensure your own `AUTH_USER_MODEL` is returned instead.

### CODE REVIEW

**Comment by tonjo** [comment]
In `test_settings.py` we had to put the app where `AUTH_USER_MODEL` is defined.
I'm thinking to enhance the customization.
I saw the django authentication backend looks for `USERNAME_FIELD`, so we can define our own.  
`AbstractBaseUser` is there exactly for that purpose, since it defines only `password`, `is_active` and `last_login`.  
Maybe we could derive from it?  
_Maybe_ we don't even need a custom backend, just a custom user, not sure about that.

**Comment by tonjo** [comment]
Did you have a look at this, @mhluongo? 
It fixes the wrong type when authenticating.
Reading the doc it seems the issue is only with Django 1.4, but it's still present in 1.5.

**Comment by mhluongo** [comment]
@tonjo This is a backwards-incompatible change- maybe there's a less heavy-handed approach? Eg by testing the import, like

```
try:
    from django.contrib.auth import get_user_model
    UserModel = get_user_model()
except ImportError:
    from .models import User as UserModel
```

**Comment by mhluongo** [comment]
I'd rather keep support for Django 1.4 _and_ support 1.5, rather than just 1.5.

**Comment by tonjo** [comment]
Yes, you're right, forgot `get_user_model` was added in 1.5. 
Changed as you suggested.

**Comment by mhluongo** [comment]
Thanks @tonjo!

**Comment by tonjo** [comment]
You're welcome.
Sorry for the little mess, still quite new at github.

**Comment by mhluongo** [comment]
No worries, you'll get the hang of it :)

**Pull request merged**
